export function contact() {
    const element = Cpasreact.createElement("div", null,
        Cpasreact.createElement("h3", null, ['Contact'].join(" ")),
        Cpasreact.createElement("p", null, ['Développer : '].join(" ")),
        Cpasreact.createElement("div", {style: 'margin-left: 1em;'},
            Cpasreact.createElement("a", {href : 'https://github.com/TheoLGG'}, ['Legagneur Théo'].join(" ")),
            Cpasreact.createElement("div", {style: 'margin-left: 1em;'},
                Cpasreact.createElement("p", null, ['06 10 25 46 06'].join(" ")),
                Cpasreact.createElement("p", null, ['theo.legagneur@gmail.com'].join(" ")),
            ),
            Cpasreact.createElement("a", {href : 'https://github.com/alexxandre80'}, ['Mandra Alexandre'].join(" ")),
            Cpasreact.createElement("div", {style: 'margin-left: 1em;'},
                Cpasreact.createElement("p", null, ['06 30 05 97 88'].join(" ")),
                Cpasreact.createElement("p", null, ['amandrake80@gmail.com'].join(" ")),
            ),
            Cpasreact.createElement("a", {href : 'https://github.com/marting37'}, ['Genot Martin'].join(" ")),
            Cpasreact.createElement("div", {style: 'margin-left: 1em;'},
                Cpasreact.createElement("p", null, ['06 99 81 21 17'].join(" ")),
                Cpasreact.createElement("p", null, ['genotmartin1@gmail.com'].join(" ")),
            ),
            Cpasreact.createElement("a", {href : 'https://github.com/MackMix'}, ['Huet Maxime'].join(" ")),
            Cpasreact.createElement("div", {style: 'margin-left: 1em;'},
                Cpasreact.createElement("p", null, ['06 75 53 09 03'].join(" ")),
                Cpasreact.createElement("p", null, ['mhuet1@myges.fr'].join(" ")),
            ),
        ),
    );
    Cpasreact.render(element, document.getElementById("root"));
}